#!/usr/bin/env python

import sys

from spot_estop_rqt.spot_estop_rqt import EstopRqtPlugin
from rqt_gui.main import Main

plugin = 'spot_estop_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
