// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bosdyn/api/auth.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_bosdyn_2fapi_2fauth_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_bosdyn_2fapi_2fauth_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "bosdyn/api/header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_bosdyn_2fapi_2fauth_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_bosdyn_2fapi_2fauth_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_bosdyn_2fapi_2fauth_2eproto;
namespace bosdyn {
namespace api {
class GetAuthTokenRequest;
struct GetAuthTokenRequestDefaultTypeInternal;
extern GetAuthTokenRequestDefaultTypeInternal _GetAuthTokenRequest_default_instance_;
class GetAuthTokenResponse;
struct GetAuthTokenResponseDefaultTypeInternal;
extern GetAuthTokenResponseDefaultTypeInternal _GetAuthTokenResponse_default_instance_;
}  // namespace api
}  // namespace bosdyn
PROTOBUF_NAMESPACE_OPEN
template<> ::bosdyn::api::GetAuthTokenRequest* Arena::CreateMaybeMessage<::bosdyn::api::GetAuthTokenRequest>(Arena*);
template<> ::bosdyn::api::GetAuthTokenResponse* Arena::CreateMaybeMessage<::bosdyn::api::GetAuthTokenResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bosdyn {
namespace api {

enum GetAuthTokenResponse_Status : int {
  GetAuthTokenResponse_Status_STATUS_UNKNOWN = 0,
  GetAuthTokenResponse_Status_STATUS_OK = 1,
  GetAuthTokenResponse_Status_STATUS_INVALID_LOGIN = 2,
  GetAuthTokenResponse_Status_STATUS_INVALID_TOKEN = 3,
  GetAuthTokenResponse_Status_STATUS_TEMPORARILY_LOCKED_OUT = 4,
  GetAuthTokenResponse_Status_STATUS_INVALID_APPLICATION_TOKEN = 5,
  GetAuthTokenResponse_Status_STATUS_EXPIRED_APPLICATION_TOKEN = 6,
  GetAuthTokenResponse_Status_GetAuthTokenResponse_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GetAuthTokenResponse_Status_GetAuthTokenResponse_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GetAuthTokenResponse_Status_IsValid(int value);
constexpr GetAuthTokenResponse_Status GetAuthTokenResponse_Status_Status_MIN = GetAuthTokenResponse_Status_STATUS_UNKNOWN;
constexpr GetAuthTokenResponse_Status GetAuthTokenResponse_Status_Status_MAX = GetAuthTokenResponse_Status_STATUS_EXPIRED_APPLICATION_TOKEN;
constexpr int GetAuthTokenResponse_Status_Status_ARRAYSIZE = GetAuthTokenResponse_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GetAuthTokenResponse_Status_descriptor();
template<typename T>
inline const std::string& GetAuthTokenResponse_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GetAuthTokenResponse_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GetAuthTokenResponse_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GetAuthTokenResponse_Status_descriptor(), enum_t_value);
}
inline bool GetAuthTokenResponse_Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GetAuthTokenResponse_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GetAuthTokenResponse_Status>(
    GetAuthTokenResponse_Status_descriptor(), name, value);
}
// ===================================================================

class GetAuthTokenRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bosdyn.api.GetAuthTokenRequest) */ {
 public:
  inline GetAuthTokenRequest() : GetAuthTokenRequest(nullptr) {}
  ~GetAuthTokenRequest() override;
  explicit PROTOBUF_CONSTEXPR GetAuthTokenRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetAuthTokenRequest(const GetAuthTokenRequest& from);
  GetAuthTokenRequest(GetAuthTokenRequest&& from) noexcept
    : GetAuthTokenRequest() {
    *this = ::std::move(from);
  }

  inline GetAuthTokenRequest& operator=(const GetAuthTokenRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetAuthTokenRequest& operator=(GetAuthTokenRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetAuthTokenRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetAuthTokenRequest* internal_default_instance() {
    return reinterpret_cast<const GetAuthTokenRequest*>(
               &_GetAuthTokenRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetAuthTokenRequest& a, GetAuthTokenRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetAuthTokenRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetAuthTokenRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetAuthTokenRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetAuthTokenRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetAuthTokenRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetAuthTokenRequest& from) {
    GetAuthTokenRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetAuthTokenRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bosdyn.api.GetAuthTokenRequest";
  }
  protected:
  explicit GetAuthTokenRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 2,
    kPasswordFieldNumber = 3,
    kTokenFieldNumber = 4,
    kApplicationTokenFieldNumber = 5,
    kHeaderFieldNumber = 1,
  };
  // string username = 2;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string password = 3;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string token = 4;
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // string application_token = 5 [deprecated = true];
  PROTOBUF_DEPRECATED void clear_application_token();
  PROTOBUF_DEPRECATED const std::string& application_token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  PROTOBUF_DEPRECATED void set_application_token(ArgT0&& arg0, ArgT... args);
  PROTOBUF_DEPRECATED std::string* mutable_application_token();
  PROTOBUF_NODISCARD PROTOBUF_DEPRECATED std::string* release_application_token();
  PROTOBUF_DEPRECATED void set_allocated_application_token(std::string* application_token);
  private:
  const std::string& _internal_application_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_application_token(const std::string& value);
  std::string* _internal_mutable_application_token();
  public:

  // .bosdyn.api.RequestHeader header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::bosdyn::api::RequestHeader& header() const;
  PROTOBUF_NODISCARD ::bosdyn::api::RequestHeader* release_header();
  ::bosdyn::api::RequestHeader* mutable_header();
  void set_allocated_header(::bosdyn::api::RequestHeader* header);
  private:
  const ::bosdyn::api::RequestHeader& _internal_header() const;
  ::bosdyn::api::RequestHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::bosdyn::api::RequestHeader* header);
  ::bosdyn::api::RequestHeader* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:bosdyn.api.GetAuthTokenRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr application_token_;
    ::bosdyn::api::RequestHeader* header_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bosdyn_2fapi_2fauth_2eproto;
};
// -------------------------------------------------------------------

class GetAuthTokenResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bosdyn.api.GetAuthTokenResponse) */ {
 public:
  inline GetAuthTokenResponse() : GetAuthTokenResponse(nullptr) {}
  ~GetAuthTokenResponse() override;
  explicit PROTOBUF_CONSTEXPR GetAuthTokenResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetAuthTokenResponse(const GetAuthTokenResponse& from);
  GetAuthTokenResponse(GetAuthTokenResponse&& from) noexcept
    : GetAuthTokenResponse() {
    *this = ::std::move(from);
  }

  inline GetAuthTokenResponse& operator=(const GetAuthTokenResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetAuthTokenResponse& operator=(GetAuthTokenResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetAuthTokenResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetAuthTokenResponse* internal_default_instance() {
    return reinterpret_cast<const GetAuthTokenResponse*>(
               &_GetAuthTokenResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetAuthTokenResponse& a, GetAuthTokenResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetAuthTokenResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetAuthTokenResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetAuthTokenResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetAuthTokenResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetAuthTokenResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetAuthTokenResponse& from) {
    GetAuthTokenResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetAuthTokenResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bosdyn.api.GetAuthTokenResponse";
  }
  protected:
  explicit GetAuthTokenResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef GetAuthTokenResponse_Status Status;
  static constexpr Status STATUS_UNKNOWN =
    GetAuthTokenResponse_Status_STATUS_UNKNOWN;
  static constexpr Status STATUS_OK =
    GetAuthTokenResponse_Status_STATUS_OK;
  static constexpr Status STATUS_INVALID_LOGIN =
    GetAuthTokenResponse_Status_STATUS_INVALID_LOGIN;
  static constexpr Status STATUS_INVALID_TOKEN =
    GetAuthTokenResponse_Status_STATUS_INVALID_TOKEN;
  static constexpr Status STATUS_TEMPORARILY_LOCKED_OUT =
    GetAuthTokenResponse_Status_STATUS_TEMPORARILY_LOCKED_OUT;
  static constexpr Status STATUS_INVALID_APPLICATION_TOKEN =
    GetAuthTokenResponse_Status_STATUS_INVALID_APPLICATION_TOKEN;
  static constexpr Status STATUS_EXPIRED_APPLICATION_TOKEN =
    GetAuthTokenResponse_Status_STATUS_EXPIRED_APPLICATION_TOKEN;
  static inline bool Status_IsValid(int value) {
    return GetAuthTokenResponse_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    GetAuthTokenResponse_Status_Status_MIN;
  static constexpr Status Status_MAX =
    GetAuthTokenResponse_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    GetAuthTokenResponse_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return GetAuthTokenResponse_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return GetAuthTokenResponse_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Status* value) {
    return GetAuthTokenResponse_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTokenFieldNumber = 3,
    kHeaderFieldNumber = 1,
    kStatusFieldNumber = 2,
  };
  // string token = 3;
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // .bosdyn.api.ResponseHeader header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::bosdyn::api::ResponseHeader& header() const;
  PROTOBUF_NODISCARD ::bosdyn::api::ResponseHeader* release_header();
  ::bosdyn::api::ResponseHeader* mutable_header();
  void set_allocated_header(::bosdyn::api::ResponseHeader* header);
  private:
  const ::bosdyn::api::ResponseHeader& _internal_header() const;
  ::bosdyn::api::ResponseHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::bosdyn::api::ResponseHeader* header);
  ::bosdyn::api::ResponseHeader* unsafe_arena_release_header();

  // .bosdyn.api.GetAuthTokenResponse.Status status = 2;
  void clear_status();
  ::bosdyn::api::GetAuthTokenResponse_Status status() const;
  void set_status(::bosdyn::api::GetAuthTokenResponse_Status value);
  private:
  ::bosdyn::api::GetAuthTokenResponse_Status _internal_status() const;
  void _internal_set_status(::bosdyn::api::GetAuthTokenResponse_Status value);
  public:

  // @@protoc_insertion_point(class_scope:bosdyn.api.GetAuthTokenResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
    ::bosdyn::api::ResponseHeader* header_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bosdyn_2fapi_2fauth_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetAuthTokenRequest

// .bosdyn.api.RequestHeader header = 1;
inline bool GetAuthTokenRequest::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool GetAuthTokenRequest::has_header() const {
  return _internal_has_header();
}
inline const ::bosdyn::api::RequestHeader& GetAuthTokenRequest::_internal_header() const {
  const ::bosdyn::api::RequestHeader* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::bosdyn::api::RequestHeader&>(
      ::bosdyn::api::_RequestHeader_default_instance_);
}
inline const ::bosdyn::api::RequestHeader& GetAuthTokenRequest::header() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.GetAuthTokenRequest.header)
  return _internal_header();
}
inline void GetAuthTokenRequest::unsafe_arena_set_allocated_header(
    ::bosdyn::api::RequestHeader* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bosdyn.api.GetAuthTokenRequest.header)
}
inline ::bosdyn::api::RequestHeader* GetAuthTokenRequest::release_header() {
  
  ::bosdyn::api::RequestHeader* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::bosdyn::api::RequestHeader* GetAuthTokenRequest::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:bosdyn.api.GetAuthTokenRequest.header)
  
  ::bosdyn::api::RequestHeader* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::bosdyn::api::RequestHeader* GetAuthTokenRequest::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::bosdyn::api::RequestHeader>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::bosdyn::api::RequestHeader* GetAuthTokenRequest::mutable_header() {
  ::bosdyn::api::RequestHeader* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:bosdyn.api.GetAuthTokenRequest.header)
  return _msg;
}
inline void GetAuthTokenRequest::set_allocated_header(::bosdyn::api::RequestHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header));
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.GetAuthTokenRequest.header)
}

// string username = 2;
inline void GetAuthTokenRequest::clear_username() {
  _impl_.username_.ClearToEmpty();
}
inline const std::string& GetAuthTokenRequest::username() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.GetAuthTokenRequest.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetAuthTokenRequest::set_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bosdyn.api.GetAuthTokenRequest.username)
}
inline std::string* GetAuthTokenRequest::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:bosdyn.api.GetAuthTokenRequest.username)
  return _s;
}
inline const std::string& GetAuthTokenRequest::_internal_username() const {
  return _impl_.username_.Get();
}
inline void GetAuthTokenRequest::_internal_set_username(const std::string& value) {
  
  _impl_.username_.Set(value, GetArenaForAllocation());
}
inline std::string* GetAuthTokenRequest::_internal_mutable_username() {
  
  return _impl_.username_.Mutable(GetArenaForAllocation());
}
inline std::string* GetAuthTokenRequest::release_username() {
  // @@protoc_insertion_point(field_release:bosdyn.api.GetAuthTokenRequest.username)
  return _impl_.username_.Release();
}
inline void GetAuthTokenRequest::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  _impl_.username_.SetAllocated(username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.GetAuthTokenRequest.username)
}

// string password = 3;
inline void GetAuthTokenRequest::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& GetAuthTokenRequest::password() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.GetAuthTokenRequest.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetAuthTokenRequest::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bosdyn.api.GetAuthTokenRequest.password)
}
inline std::string* GetAuthTokenRequest::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:bosdyn.api.GetAuthTokenRequest.password)
  return _s;
}
inline const std::string& GetAuthTokenRequest::_internal_password() const {
  return _impl_.password_.Get();
}
inline void GetAuthTokenRequest::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* GetAuthTokenRequest::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* GetAuthTokenRequest::release_password() {
  // @@protoc_insertion_point(field_release:bosdyn.api.GetAuthTokenRequest.password)
  return _impl_.password_.Release();
}
inline void GetAuthTokenRequest::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.GetAuthTokenRequest.password)
}

// string token = 4;
inline void GetAuthTokenRequest::clear_token() {
  _impl_.token_.ClearToEmpty();
}
inline const std::string& GetAuthTokenRequest::token() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.GetAuthTokenRequest.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetAuthTokenRequest::set_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bosdyn.api.GetAuthTokenRequest.token)
}
inline std::string* GetAuthTokenRequest::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:bosdyn.api.GetAuthTokenRequest.token)
  return _s;
}
inline const std::string& GetAuthTokenRequest::_internal_token() const {
  return _impl_.token_.Get();
}
inline void GetAuthTokenRequest::_internal_set_token(const std::string& value) {
  
  _impl_.token_.Set(value, GetArenaForAllocation());
}
inline std::string* GetAuthTokenRequest::_internal_mutable_token() {
  
  return _impl_.token_.Mutable(GetArenaForAllocation());
}
inline std::string* GetAuthTokenRequest::release_token() {
  // @@protoc_insertion_point(field_release:bosdyn.api.GetAuthTokenRequest.token)
  return _impl_.token_.Release();
}
inline void GetAuthTokenRequest::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  _impl_.token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.GetAuthTokenRequest.token)
}

// string application_token = 5 [deprecated = true];
inline void GetAuthTokenRequest::clear_application_token() {
  _impl_.application_token_.ClearToEmpty();
}
inline const std::string& GetAuthTokenRequest::application_token() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.GetAuthTokenRequest.application_token)
  return _internal_application_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetAuthTokenRequest::set_application_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.application_token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bosdyn.api.GetAuthTokenRequest.application_token)
}
inline std::string* GetAuthTokenRequest::mutable_application_token() {
  std::string* _s = _internal_mutable_application_token();
  // @@protoc_insertion_point(field_mutable:bosdyn.api.GetAuthTokenRequest.application_token)
  return _s;
}
inline const std::string& GetAuthTokenRequest::_internal_application_token() const {
  return _impl_.application_token_.Get();
}
inline void GetAuthTokenRequest::_internal_set_application_token(const std::string& value) {
  
  _impl_.application_token_.Set(value, GetArenaForAllocation());
}
inline std::string* GetAuthTokenRequest::_internal_mutable_application_token() {
  
  return _impl_.application_token_.Mutable(GetArenaForAllocation());
}
inline std::string* GetAuthTokenRequest::release_application_token() {
  // @@protoc_insertion_point(field_release:bosdyn.api.GetAuthTokenRequest.application_token)
  return _impl_.application_token_.Release();
}
inline void GetAuthTokenRequest::set_allocated_application_token(std::string* application_token) {
  if (application_token != nullptr) {
    
  } else {
    
  }
  _impl_.application_token_.SetAllocated(application_token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.application_token_.IsDefault()) {
    _impl_.application_token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.GetAuthTokenRequest.application_token)
}

// -------------------------------------------------------------------

// GetAuthTokenResponse

// .bosdyn.api.ResponseHeader header = 1;
inline bool GetAuthTokenResponse::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool GetAuthTokenResponse::has_header() const {
  return _internal_has_header();
}
inline const ::bosdyn::api::ResponseHeader& GetAuthTokenResponse::_internal_header() const {
  const ::bosdyn::api::ResponseHeader* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::bosdyn::api::ResponseHeader&>(
      ::bosdyn::api::_ResponseHeader_default_instance_);
}
inline const ::bosdyn::api::ResponseHeader& GetAuthTokenResponse::header() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.GetAuthTokenResponse.header)
  return _internal_header();
}
inline void GetAuthTokenResponse::unsafe_arena_set_allocated_header(
    ::bosdyn::api::ResponseHeader* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bosdyn.api.GetAuthTokenResponse.header)
}
inline ::bosdyn::api::ResponseHeader* GetAuthTokenResponse::release_header() {
  
  ::bosdyn::api::ResponseHeader* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::bosdyn::api::ResponseHeader* GetAuthTokenResponse::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:bosdyn.api.GetAuthTokenResponse.header)
  
  ::bosdyn::api::ResponseHeader* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::bosdyn::api::ResponseHeader* GetAuthTokenResponse::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::bosdyn::api::ResponseHeader>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::bosdyn::api::ResponseHeader* GetAuthTokenResponse::mutable_header() {
  ::bosdyn::api::ResponseHeader* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:bosdyn.api.GetAuthTokenResponse.header)
  return _msg;
}
inline void GetAuthTokenResponse::set_allocated_header(::bosdyn::api::ResponseHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header));
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.GetAuthTokenResponse.header)
}

// .bosdyn.api.GetAuthTokenResponse.Status status = 2;
inline void GetAuthTokenResponse::clear_status() {
  _impl_.status_ = 0;
}
inline ::bosdyn::api::GetAuthTokenResponse_Status GetAuthTokenResponse::_internal_status() const {
  return static_cast< ::bosdyn::api::GetAuthTokenResponse_Status >(_impl_.status_);
}
inline ::bosdyn::api::GetAuthTokenResponse_Status GetAuthTokenResponse::status() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.GetAuthTokenResponse.status)
  return _internal_status();
}
inline void GetAuthTokenResponse::_internal_set_status(::bosdyn::api::GetAuthTokenResponse_Status value) {
  
  _impl_.status_ = value;
}
inline void GetAuthTokenResponse::set_status(::bosdyn::api::GetAuthTokenResponse_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.GetAuthTokenResponse.status)
}

// string token = 3;
inline void GetAuthTokenResponse::clear_token() {
  _impl_.token_.ClearToEmpty();
}
inline const std::string& GetAuthTokenResponse::token() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.GetAuthTokenResponse.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetAuthTokenResponse::set_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bosdyn.api.GetAuthTokenResponse.token)
}
inline std::string* GetAuthTokenResponse::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:bosdyn.api.GetAuthTokenResponse.token)
  return _s;
}
inline const std::string& GetAuthTokenResponse::_internal_token() const {
  return _impl_.token_.Get();
}
inline void GetAuthTokenResponse::_internal_set_token(const std::string& value) {
  
  _impl_.token_.Set(value, GetArenaForAllocation());
}
inline std::string* GetAuthTokenResponse::_internal_mutable_token() {
  
  return _impl_.token_.Mutable(GetArenaForAllocation());
}
inline std::string* GetAuthTokenResponse::release_token() {
  // @@protoc_insertion_point(field_release:bosdyn.api.GetAuthTokenResponse.token)
  return _impl_.token_.Release();
}
inline void GetAuthTokenResponse::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  _impl_.token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.GetAuthTokenResponse.token)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace api
}  // namespace bosdyn

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::bosdyn::api::GetAuthTokenResponse_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bosdyn::api::GetAuthTokenResponse_Status>() {
  return ::bosdyn::api::GetAuthTokenResponse_Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_bosdyn_2fapi_2fauth_2eproto
