# This is an example configuration file for Spot.  It is not used!

/**:
  ros__parameters:
    rates:
      robot_state: 10.0
      metrics: 0.04
      lease: 1.0
      front_image: 10.0
      side_image: 10.0
      rear_image: 10.0
    auto_claim: True
    auto_power_on: True
    auto_stand: False
    deadzone: 0.05
    estop_timeout: 10.0
    start_estop: False
    rgb_cameras: False
    publish_rgb: False
    publish_depth: False
    publish_depth_registered: False
    preferred_odom_frame: "vision"
    cmd_duration: 0.4
    async_tasks_rate: 30
